version: '3.8'
services:

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    environment:
      - REDIS_USER=dev
      - PASSWORD=dev123
    ports:
      - '6379:6379'

  python3:
    build: .
    container_name: python3
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    ports:
      - 5000:5000
